"""add scan blocked_reason column

Revision ID: 5489f2b2b01a
Revises: aef5c2b7f379
Create Date: 2026-08-13 16:14:10.778474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5489f2b2b01a'
down_revision: Union[str, Sequence[str], None] = 'aef5c2b7f379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('blocked_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'blocked_reason')
    # ### end Alembic commands ###
